/*globals CoreCircsim*/

CoreCircsim = SC.Object.create({

    /*
     * The following line would populate the records database (store) from the
     * fixtures found in frameworks/core_circsim/fixtures, which in turn were
     * generated by the build_circsim script. Use it in place of the emtpy
     * create() call it if this behavior is desired, such as for testing using a
     * static source of information for the simulation procedures. However, the
     * intended behavior is to load the procedure information dynamically (found
     * in core_loader.js).
     */
    // store: SC.Store.create().from(SC.Record.fixtures)
    store : SC.Store.create()

});
